name: Update docker image

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_image ./app

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mlops_image

      - name: Remove previous image
        run: |
          docker kill jj_mlops
        continue-on-error: true

      - name: Deploy on server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -o StrictHostKeyChecking=no << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/mlops_image
            docker run --rm --name jj_mlops -d -p 6033:8000 ${{ secrets.DOCKER_USERNAME }}/mlops_image
          EOF
